### ISSUE TITLE
Still decryptable

### ISSUE THREAD

**Issue by LGLTeam** [adamyaxley/Obfuscate#15]
Someone send me this image, seems 64-bit key is easly decryptable. Is there more ways you can improve more? and break IDA's pseduocode?

![image](https://user-images.githubusercontent.com/61142621/123213428-491a3700-d4c6-11eb-9f19-c94f15742c19.png)

**Comment by ZMODs** [comment]
is AY obfuscator really that insecure? I might gonna switch to better ones

**Comment by LGLTeam** [comment]
Yes, it's a lot easier to decrypt than you expected. Another one showed me how easy it is to decrypt with no effort, no matter if it has 64-bit key, i'm not gonna show here
So i requested to break and confuse pseduocode as possible

**Comment by MarioLiebisch** [comment]
Correct me if I'm wrong, but I think you're both missing the point here. This library isn't about cryptographic security to protect things like API keys or codes against people who know what they're doing, because that's something you can never really achieve. Just look at (really expensive) middleware such as Denuvo. In case of this library here, it's really just about hiding string literals from binary files, avoiding the most basic form of "open the file and look for it". If you don't want something exposed under any circumstances, don't include it in the first place. (Instead add an additional layer, e.g. a web service handling the protected request.)

Also: You don't even have to use a decompiler to find encrypted strings. All you have to do is run the program as usual and look through memory after the mentioned string has been used/deobfuscated. I think the readme should make this more clear.

**Comment by adamyaxley** [comment]
Hi all,

Like @MarioLiebisch mentioned, this intent of this library is to not expose string literals as plain text in the binary. It should not be used to obfuscate secret information. Designing your application to not store secrets in the code in any form is the only way to keep them secret, no matter how well it is obfuscated. Obfuscation will only slow down attackers, it won't stop them. I agree, that we should update the readme to make this more clear.

@LGLTeam What kind of attacks are you trying to protect against? If you wanted to make the obfuscation more complicated, you could edit ay::cipher().

Thanks,
Adam

**Comment by LGLTeam** [comment]
Just wanted to protect against IDA pseduocode, so it's not easy to do something you may know. it's not a problem if you don't wanna improve it. I don't have knowledge in xor and encryption, so we will live with it :)

We are using Android platform, such memory access and debugging is not always an easy thing on Android even though you have root permission due to system protection, unlike PC which is a lot easier. Nothing much secrets on c++ side other than offsets, it was basically meant to prevent stealing offsets and editing. Obfuscator is still useful to prevent script kiddies who like to edit credits directly in binary, just saying.

**Comment by MarioLiebisch** [comment]
> Nothing much secrets on c++ side other than offsets, it was basically meant to prevent stealing offsets and editing.
No idea what kind of offsets, but just rotating numbers by a single bit can make identifying them a lot more complicated. Remember that it's one thing to get your source code numbers in disassembly. Actually interpreting them is the harder part.

> Obfuscator is still useful to prevent script kiddies who like to edit credits directly in binary, just saying.
Yes, that would be a perfectly valid use case for this library.
