### ISSUE TITLE
How do I dissembler/decompile to check whether it is working?

### ISSUE THREAD

**Issue by Taymindis** [adamyaxley/Obfuscate#2]

**Comment by adamyaxley** [comment]
On Windows you can download the strings program from www.sysinternals.com and then use that to search for your hidden strings in the outputted binary. For example if I wanted to check whether or not "password" was stored in plain text in app.exe I could do the following:

strings app.exe | find "password"

If nothing is printed out, then the string hasn't been found.

On Linux the process is similar but instead of using find you use grep.
