### ISSUE TITLE
Default key is deterministic and extremely short.

### ISSUE THREAD

**Issue by EspoTek** [adamyaxley/Obfuscate#3]
https://github.com/adamyaxley/Obfuscate/blob/88915d0afa46448570207e36aa8cc5f714709c50/obfuscate.h#L151

Looks like the `AY_OBFUSCATE` macro uses the key `.` by default.
This makes decrypting the strings trivially easy (just xor each byte of the executable with `.` and you have the plaintext).

Generating the key at compile time and many characters long will make protect the strings from this kind of basic attack.

**Comment by adamyaxley** [comment]
Thanks for logging EspoTek.

Indeed it would be easy to protect against this kind of attack by randomising the key at compile time and making it longer. However, no amount of obfuscation will 100% protect the string from adamant hackers, as the strings will also appear in plain text in memory when decrypted - so for any highly sensitive strings it is not recommended to store them in the binary in any form.

I may have time in the next couple of weeks to have a look at this issue, if that is too long and you have any ideas please feel free to contribute and open a pull request. :)

**Comment by EspoTek** [comment]
Understand.  One simple way of mitigating this risk would be to simply change the readme.md to recommend that the user provide their own randomly generated key with a length >= the length of the longest string they obfuscate.

The way it's written now, it seems to imply that all you need to do is wrap your strings in that macro and you're safe.

**Comment by adamyaxley** [comment]
> Looks like the AY_OBFUSCATE macro uses the key . by default.
This makes decrypting the strings trivially easy (just xor each byte of the executable with . and you have the plaintext).

I tried doing this and found that for small strings, the compiler tends not to store them in static storage but to actually build them up at runtime in a series of mov assembly operations. The compiler can do this because the obfuscation process doesn't require a const pointer to the string, so static storage doesn't need to be used. However, for larger strings (above approximately 75 characters), it appeared that the encrypted version of the string was more often stored as static data in the binary, potentially for optimisation reasons, which resulted in it being susceptible to this attack.

AY_OBFUSCATE only supports single character XOR encryption, but that appears to be good enough for small strings at least. As you say, it would be better to suggest in the README to use a random key generated at compile time.

**Comment by adamyaxley** [comment]
EspoTek thank you so much for this great feedback! I've updated the README and will close this issue now.

**Comment by LegendaryB** [comment]
Hey,

thanks for sharing your code. Any sample how to do that?
