### ISSUE TITLE
VMProtect

### ISSUE THREAD

**Issue by CSGO01** [adamyaxley/Obfuscate#35]
Can I use it this way? VMProtectDecryptStringA (AY_OBFUSCATE ("test"))
The string is not recognized in the GUI I sent VMP

**Comment by adamyaxley** [comment]
Hi CSGO01,

I haven't tried using VMProtect myself but I understand that VMProtectDecryptStringA is decrypting an encrypted string constant, so it looks like VMProtect includes a string obfuscation mechanism already.

I recommend you to use the functionality VMProtect offers instead of this library.

Thanks,
Adam
