### ISSUE TITLE
Can't convert to NSString

### ISSUE THREAD

**Issue by Toshiba1127** [adamyaxley/Obfuscate#6]
I'm developing tweak for iOS but i can't apply string obfuscation with NSString. Can you add support for it?

```
> Making all for tweak tweaker…
==> Preprocessing Tweak.xm…
==> Compiling Tweak.xm (arm64)…
Tweak.xm:98:22: error: no viable conversion from 'ay::obfuscated_data<sizeof
      ("string test") / sizeof ("string test"[0]), ','>' to 'NSString *'
            subTitle:O("string test")
                     ^~~~~~~~~~~~~~~~
/Volumes/iOS/tweaker/Includes/obfuscate.h:158:17: note: expanded from macro
      'O'
#define O(data) O_KEY(data, ',')
                ^~~~~~~~~~~~~~~~
/Volumes/iOS/tweaker/Includes/obfuscate.h:165:2: note: expanded from macro
      'O_KEY'
        []() -> ay::obfuscated_data<sizeof(data)/sizeof(data[0]), key>& { \
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Volumes/iOS/tweaker/Includes/obfuscate.h:96:3: note: candidate function
                operator char*()
                ^
/Volumes/iOS/tweaker/Includes/obfuscate.h:102:3: note: candidate function
                operator std::string()
                ^
/Volumes/iOS/tweaker/SCLAlertView/SCLAlertView.h:366:60: note: passing
      argument to parameter 'subTitle' here
- (void)showSuccess:(NSString *)title subTitle:(NSString *)subTitle clos...
                                                           ^
1 error generated.
make[3]: *** [/Volumes/iOS/tweaker/.theos/obj/arm64/Tweak.xm.1d85f210.o] Error 1
make[2]: *** [/Volumes/iOS/tweaker/.theos/obj/arm64/tweaker.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [tweaker.all.tweak.variables] Error 2

```

**Comment by MarioLiebisch** [comment]
You're trying to assign a string literal/character pointer (`char*`) to a pointer for a class object (`NSString*`).
That won't work and is – to my limited Mac/iOS experience – impossible to fix in this header (in an elegant way).

You'd have to do something like this, if you absolutely have to use a pointer:

```cpp
NSString myString(O("my obfuscated text")); // Create a NSString object you can point to
myFunctionExpectingAPointer(&myString); // Now use the pointer
```

**Comment by adamyaxley** [comment]
Thanks for the question @Toshiba1127 and for the answer @MarioLiebisch which would be my recommended way to do it.

As an alternative solution you could use a function level static in an unnamed lambda to store the NSString. This would guarantee lifetime of the object so that it doesn't get freed early and result in a dangling pointer. This is actually the same trick that is used by ay::obfuscated_data.

To do this for a custom type TYPE you could try the following code, which requires the custom type to be constructable from a char*:

`#define AY_OBFUSCATE_KEY_CUSTOM_TYPE_PTR(TYPE, data, key) \
	[]() -> TYPE* { \
		constexpr auto n = sizeof(data)/sizeof(data[0]); \
		static_assert(data[n - 1] == '\0', "String must be null terminated"); \
		constexpr auto obfuscator = ay::make_obfuscator<n, key>(data); \
		auto obfuscated_data = ay::obfuscated_data<n, key>(obfuscator); \
		static TYPE obfuscated_data_custom_type(obfuscated_data); \
		return &obfuscated_data_custom_type; \
	}()`

Then you would use it like:

`NSString* string_ptr = AY_OBFUSCATE_KEY_CUSTOM_TYPE_PTR(NSString, "Hello World", '.');`

**Comment by Toshiba1127** [comment]
Thanks guys, very helpful
Another way is to obfuscate std::string then convert std::string to NSString, it works too =D
