### ISSUE TITLE
Improve obfuscation

### ISSUE THREAD

**Issue by LGLTeam** [adamyaxley/Obfuscate#8]
Someone told me AY obfuscator is easy to decrypt in IDA as the key was there but for me, i can't see anyway to decrypt in IDA. Can you possibly improve it more and allow more letters than one for the key?

**Comment by adamyaxley** [comment]
Hi LGLTeam,

Thanks for reporting, I see that it is possible to inspect the key in the assembly. To fix this and also make it harder to work out what the key is, I've increased its size to 64 bits. The key is split up during decryption so it is no longer present in plain text in the binary.

The reason why I chose a 64 bit int over a string representation for the key is because if I used a string I would need to obfuscate that string somehow, which leads us back to the original problem of string obfuscation.

See pull request #9 

It would be great to have your feedback here, so we can improve it for everyone.

Thanks,
Adam

**Comment by LGLTeam** [comment]
I'm not good in reversing but it should look harder to reverse via IDA
Your changes still working fine so far

**Comment by LGLTeam** [comment]
Btw, you should update the README about the 64-bit key

**Comment by adamyaxley** [comment]
Thanks for checking. I've merged the changes to the master branch. Note that the key can still sometimes be viewable in the assembly in one of the following two situations:

1. A long string is being obfuscated, which can cause some compilers to save the entire key.
2. Symbols are not stripped from the binary. The key is a template parameter so it may be visible in symbol names.

Please create a new issue if you have any further suggestions. :)

**Comment by Harshkanani** [comment]
> Someone told me AY obfuscator is easy to decrypt in IDA as the key was there but for me, i can't see anyway to decrypt in IDA. Can you possibly improve it more and allow more letters than one for the key?

Can you tell me how to decrypt it using IDA?
